# Generated by Django 5.2.15 on 2026-06-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update_id', models.BigIntegerField(default=0, verbose_name='Последний update_id')),
            ],
            options={
                'verbose_name': 'Состояние Telegram-бота',
                'verbose_name_plural': 'Состояние Telegram-бота',
            },
        ),
    ]
