# Generated by Django 5.2.15 on 2026-06-13 00:26

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(blank=True, max_length=32, verbose_name='Telegram chat id')),
                ('link_code', models.CharField(default=apps.accounts.models.make_link_code, editable=False, max_length=32, unique=True, verbose_name='Код привязки')),
                ('linked_at', models.DateTimeField(blank=True, null=True, verbose_name='Привязан')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Telegram-профиль',
                'verbose_name_plural': 'Telegram-профили',
            },
        ),
    ]
