# Generated by Django 5.2.15 on 2026-06-10 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('network', models.CharField(blank=True, max_length=100, verbose_name='Сеть')),
                ('city', models.CharField(default='Москва', max_length=100, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('is_niche', models.BooleanField(default=False, help_text='Артхаус, ретроспективы, показы на языке оригинала', verbose_name='Нишевый')),
            ],
            options={
                'verbose_name': 'Кинотеатр',
                'verbose_name_plural': 'Кинотеатры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('original_title', models.CharField(blank=True, max_length=300, verbose_name='Оригинальное название')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год')),
                ('normalized_title', models.CharField(db_index=True, editable=False, max_length=300)),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['title'],
                'constraints': [models.UniqueConstraint(fields=('normalized_title', 'year'), name='uniq_movie_title_year')],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(db_index=True, verbose_name='Начало сеанса')),
                ('format', models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('IMAX', 'IMAX'), ('OTHER', 'Другое')], default='2D', max_length=10, verbose_name='Формат')),
                ('original_language', models.BooleanField(default=False, verbose_name='На языке оригинала')),
                ('hall', models.CharField(blank=True, max_length=100, verbose_name='Зал')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='catalog.cinema', verbose_name='Кинотеатр')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='catalog.movie', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Мин. цена, руб.')),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Макс. цена, руб.')),
                ('collected_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Собрано')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.session', verbose_name='Сеанс')),
            ],
            options={
                'verbose_name': 'Снимок цены',
                'verbose_name_plural': 'Снимки цен',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('cinema', 'movie', 'starts_at', 'format'), name='uniq_session'),
        ),
        migrations.AddIndex(
            model_name='pricesnapshot',
            index=models.Index(fields=['session', 'collected_at'], name='catalog_pri_session_6d586c_idx'),
        ),
    ]
