# Generated by Django 5.2.15 on 2026-06-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='afisha_slug',
            field=models.CharField(blank=True, help_text='Например, illyuzion-2692; заполняется автообнаружением', max_length=200, verbose_name='Слаг на Афише.ру'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='is_monitored',
            field=models.BooleanField(default=False, help_text='Опрашивать этот кинотеатр парсером afisha', verbose_name='Мониторим'),
        ),
    ]
