# Generated by Django 5.2.15 on 2026-06-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_seed_monitored_cinemas'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_special',
            field=models.BooleanField(default=False, help_text='Опера, балет, TheatreHD, экскурсии — исключается из афиши по умолчанию', verbose_name='Спецпоказ'),
        ),
    ]
