# Generated by Django 5.2.15 on 2026-06-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=50, verbose_name='Источник')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('success', 'Успех'), ('error', 'Ошибка')], default='running', max_length=10, verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Запущен')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('sessions_found', models.PositiveIntegerField(default=0, verbose_name='Сеансов обработано')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
            ],
            options={
                'verbose_name': 'Запуск парсера',
                'verbose_name_plural': 'Запуски парсеров',
                'ordering': ['-started_at'],
            },
        ),
    ]
